[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/journal/*"
  to = "/journal/[id].html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 